#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Create a backup of the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Create a new hosts file with the desired changes
echo "127.0.0.2		localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8		facebook.com" | sudo tee -a /etc/hosts
